#!/bin/bash

Description=$1
Username=$USER

if [ -z "$Description" ]; then
  Description="$(date +"%Y-%m-%d %H:%M:%S") by ${Username^}"
fi

chmod -R 0755 .

git add . && git commit -a -m "$Description"
git push --force -v origin main